### ISSUE TITLE
Improve formatting

### ISSUE THREAD

**Issue by MiguelHigueraDev** [iSlammedMyKindle/twitchToDiscordBot#26]
I think that even though the formatting is serviceable, it could be improved a lot by using a twitch emoji and a bold font for the username, like this:

![image](https://github.com/iSlammedMyKindle/twitchToDiscordBot/assets/133175356/731d0c68-8496-4747-aa41-6e4bdc43b1b6)

I think it's an upgrade over this:

![image](https://github.com/iSlammedMyKindle/twitchToDiscordBot/assets/133175356/43f67940-4705-4ca3-b749-97b7a9c4e840)

You may disagree, I would like to hear your input.

**Comment by iSlammedMyKindle** [comment]
It seems like a very interesting idea; There are a couple of things I would want to consider in order to do something like this:

* If this were configured to use discord emoji, there would need to be a place in the configuration file that would indicate which emoji to use. Since the project itself is open source, it's possible that someone else might want to deploy it, but if there was a dependency on a certain emoji and it was removed, then there could be issues sending a message
* This aesthetic looks nice, but I think another thing that would need to be done to fully keep it flush with everything would be to remove the tag if there are more subsequent messages from the same user. This could be done by tracking the last user that spoke, then omitting the username of the user if they speak again. This behavior would be similar to the [text to speech engine spaghetti code](https://github.com/iSlammedMyKindle/textToSpeechTLCModule/blob/master/index.html#L76)
* This would realistically only work with discord; it *could* be possible to do an emoji at minimum on the twitch side, but it would 99% likely just be a stock emoji, unless the account hosting the chat somehow managed to be affiliate or partner. There would be no bold formatting in twitch, but that's just because it's got IRC origins

**Comment by MiguelHigueraDev** [comment]
Ah yeah, the first point is a good one, it's something I didn't consider.

I could consider the second point as well, but I don't know if it would look good, most chat applications put the sender on every message. The other option would be to use webhooks and send a message with the twitch username instead of twitchToDis or whatever the bot is called, that would be more like Discord handles messages by the same user.

And about the third point yeah I forgot to mention it, it would be a change applied only to the Discord side of the program.

**Comment by iSlammedMyKindle** [comment]
It depends on the application from what I recall, it could probably be up for preference.

iMessage is one example where they tend to be very minimal with bubble design. They tend not to show names in the first place with 1-1s, but in group texts, they will show a bubble showing who most recently talked.

Minecraft is on the opposite spectrum, where it shows a username after every message. When I think of minecraft, it feels a lot like how IRC behaves, or twitch for that matter.

Discord will only show the username of a person after a message if there was at least 2-5 minutes of inactivity between messages. Given that twitch messages are now being sent over to discord, it might make sense to retain the paradigm that discord tries to do with minimalism and remove the username after more than one message.

Ultimately though it's up for preference, Though at the end of the day it's not super related to the minimum scope which is to format the message differently

**Comment by MiguelHigueraDev** [comment]
I would just implement it sending the username with every message and making sure there is a way to specify what emoji would be used. 

Later we could take a look into doing it using webhooks, because I think that would take a lot more time because it would need to rewrite certain parts of the code, instead of just changing the formatting and adding a property to the configuration file.

If you agree with this, I'll be glad to send you a PR with the changes.

**Comment by iSlammedMyKindle** [comment]
You're more than welcome to give it a shot! The only pre-requisite that's needed for this repo would be to make sure the bot is able to be tested & deployed using a personal dev environment. Previous contributers tried to send code without testing; so it will be asked if it's tested before merge! 👍
